dlcs:
  memoria_vectorial:
    comando_desinstalar: pip uninstall -y sentence-transformers
    comando_instalar: pip install sentence-transformers
    descripcion: "Recuerda el contexto exacto buscando matem\xE1ticamente en todo\
      \ tu historial."
    estado: activo
    nombre: Memoria Vectorial Infinita
    tipo: python_lib
  youtube:
    comando_desinstalar: pip uninstall -y youtube-transcript-api
    comando_instalar: pip install youtube-transcript-api
    descripcion: "Extrae y resume subt\xEDtulos de v\xEDdeos instant\xE1neamente."
    estado: activo
    nombre: Devorador de YouTube
    tipo: python_script
local: true
mic_index: 0
model_chat: ollama/llama3.1:8b
model_coder: ollama/qwen2.5-coder:14b
modulos:
  indice:
    estado: activo
    ruta: modulos/indice.psm1
    version: '1.0'
  memoria:
    estado: activo
    log_sesion: logs/sesion_actual.log
    modelo_resumen: ollama/qwen2.5:7b-instruct-q5_K_M
    ruta: memoria/memoria.json
    version: '1.0'
