content = open("C:\\JARVIS2\\jarvis2_installer.iss", "w", encoding="utf-8")
content.write("[Setup]\n")
content.write("AppName=JARVIS2\n")
content.write("AppVersion=1.0.0\n")
content.write("AppPublisher=Ruben Diaz\n")
content.write("DefaultDirName=C:\\JARVIS2\n")
content.write("DefaultGroupName=JARVIS2\n")
content.write("OutputDir=C:\\JARVIS2\\installer\n")
content.write("OutputBaseFilename=JARVIS2_Setup\n")
content.write("Compression=lzma\n")
content.write("SolidCompression=yes\n")
content.write("DisableDirPage=yes\n")
content.write("\n")
content.write("[Dirs]\n")
content.write('Name: "{app}\\memoria"\n')
content.write('Name: "{app}\\logs"\n')
content.write('Name: "{app}\\sandbox"\n')
content.write('Name: "{app}\\modulos"\n')
content.write("\n")
content.write("[Files]\n")
content.write('Source: "C:\\JARVIS2\\jarvis.exe";                  DestDir: "{app}";          Flags: ignoreversion\n')
content.write('Source: "C:\\JARVIS2\\jarvis.ps1";                  DestDir: "{app}";          Flags: ignoreversion\n')
content.write('Source: "C:\\JARVIS2\\launcher.py";                 DestDir: "{app}";          Flags: ignoreversion\n')
content.write('Source: "C:\\JARVIS2\\config.yaml";                 DestDir: "{app}";          Flags: ignoreversion onlyifdoesntexist\n')
content.write('Source: "C:\\JARVIS2\\system.md";                   DestDir: "{app}";          Flags: ignoreversion\n')
content.write('Source: "C:\\JARVIS2\\setup.ps1";                   DestDir: "{app}";          Flags: ignoreversion\n')
content.write('Source: "C:\\JARVIS2\\modulos\\indice.psm1";        DestDir: "{app}\\modulos"; Flags: ignoreversion\n')
content.write('Source: "C:\\JARVIS2\\memoria\\memoria.json";       DestDir: "{app}\\memoria"; Flags: ignoreversion onlyifdoesntexist\n')
content.write('Source: "C:\\JARVIS2\\memoria\\indice.json";        DestDir: "{app}\\memoria"; Flags: ignoreversion onlyifdoesntexist\n')
content.write("\n")
content.write("[Icons]\n")
content.write('Name: "{userdesktop}\\JARVIS2"; Filename: "{app}\\jarvis.exe"\n')
content.write("\n")
content.write("[Run]\n")
content.write('Filename: "powershell.exe"; Parameters: "-NoExit -ExecutionPolicy Bypass -File ""{app}\\setup.ps1"""; Description: "Configurar JARVIS2 (instalar dependencias)"; Flags: postinstall runasoriginaluser\n')
content.close()
print("OK")
